FROM adoptopenjdk/openjdk11:alpine-jre

#Install curl
RUN apk --no-cache add curl

# create the app user
RUN addgroup -S app && adduser -S app -G app

ENV APP_HOME=/home/app
WORKDIR $APP_HOME

# copy project
COPY helloworld.jar $APP_HOME/

RUN chmod -R 755 $APP_HOME

# chown all files to the app user
RUN chown -R app:app $APP_HOME

# change to the app user
USER app

# run entrypoint.prod.sh
# ENTRYPOINT ["/home/app/entrypoint.prod.sh"]

# Start app
CMD ["java", "-jar", "helloworld.jar"]
