apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: my-java-app-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: my-java-app-deployment
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 50
