apiVersion: v1
kind: Service
metadata:
  name: my-java-app-lb-service
  labels:
    app: my-java-app
spec:
  selector:
    app: my-java-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
